name: 'Issues Match Lanuages Translator'
description: 'The action for translate match lanuages issues content to English.'
author: 'a631807682'
branding:
  icon: 'book-open'
  color: 'blue'
inputs:
  github-token:
    required: true
    description: 'Action identity GITHUB_TOKEN'
  match-languages:
    required: false
    description: 'Match languages which will be translate'
    default: 'cmn'
  min-match-percent:
    required: false
    description: 'The percent of match languages needs to be greater than this percent'
    default: '0'
  modify-title:
    required: false
    description: 'Should modify issue title'
    default: 'false'
  modify-body:
    required: false
    description: 'Should create comment to translate body'
    default: 'false'
  modify-comment:
    required: false
    description: 'Should create comment to translate comment'
    default: 'false'
  comment-note:
    required: false
    description: 'Bot reply template content'
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'

